// Status
export const STATUS_CONNECT = 'STATUS_CONNECT'
export const MESSAGE_STATUS = 'MESSAGE_STATUS'
export const RECEIVED = 'RECEIVED'
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE'
export const INCHAT = 'inChat'
export const QRCODE = 'QRCODE'
export const CONNECTED = 'connected'
export const BROWSER_CLOSE = 'browserClose'
export const AUTO_CLOSE_CALLED = 'autocloseCalled'
export const DESCONNECTED_MOBILE = 'desconnectedMobile'
export const NOTLOGGED = 'notLogged'
// Types
export const TEXT = 'text'
export const IMAGE = 'image'
export const BUTTONS_RESPONSE = 'buttons_response'
export const LIST_RESPONSE = 'list_response'